trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean build sonarqube'
    sonarQubeRunAnalysis: true
    sonarQubeScannerVersionChoice: 'specify'
    sonarQubeGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'

- task: Xcode@5
  inputs:
    actions: 'build'
    packageApp: false
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/app/build/outputs/apk'
    ArtifactName: 'app.apk'
    publishLocation: 'Container'